version: '3'

services:
    app:
        image: server-gcc:latest
        container_name: gcc-simple-server
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:8080"
        tty: true